# Generated by Django 4.2.7 on 2023-11-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='contatc',
            new_name='contact',
        ),
    ]
